### ISSUE TITLE
variable spelt wrong?

### ISSUE THREAD

**Issue by james-langbein** [jaymody/blogposts#2]
Hi Jay, 

I was reading your blog and spotted a potential mistake, then found my way here :)

I believe the final assignment in the Three Loop code should be 'dists' instead of 'dist'.

Thanks for the blog post, I really appreciate it, very clear explanations :)

James

**Comment by jaymody** [comment]
Oh yeah, good catch, fixed it here in this commit: https://github.com/jaymody/blogposts/commit/7798b39b7d561a1272c1cad3aa3bf5b8616a944b
